DATA_SEG SEGMENT
    SOURCE_DB DB 100H DUP (?)   ; Source data buffer
    DEST_DB   DB 100H DUP (?)   ; Destination data buffer
DATA_SEG ENDS

CODE_SEG SEGMENT
ASSUME CS:CODE_SEG, DS:DATA_SEG

START:
    MOV AX, DATA_SEG
    MOV DS, AX

    MOV SI, OFFSET SOURCE_DB
    MOV CX, 100H
    MOV AL, 01H
REPEAT_SRC:
    MOV [SI], AL
    INC SI
    LOOP REPEAT_SRC

    MOV SI, OFFSET SOURCE_DB
    MOV DI, OFFSET DEST_DB
    MOV CX, 100H
REPEAT_TRANSFER:
    MOV AL, [SI]
    MOV [DI], AL
    INC SI
    INC DI
    LOOP REPEAT_TRANSFER

    MOV AH, 4CH
    INT 21H

CODE_SEG ENDS
END START
