DATA_SEG SEGMENT
    NUMBERS DB 10, 20, 15, 30, 25, 40, 35, 50, 45, 5
    NUM_COUNT DB 10
    MAX_NUM DB ?
DATA_SEG ENDS

CODE_SEG SEGMENT
ASSUME CS:CODE_SEG, DS:DATA_SEG

START:
    MOV AX, DATA_SEG
    MOV DS, AX
    MOV SI, 0
    MOV CL, NUM_COUNT
    MOV AL, [NUMBERS]
    MOV MAX_NUM, AL

FIND_MAX:
    INC SI
    CMP AL, [NUMBERS + SI]
    JAE NOT_LARGER
    MOV AL, [NUMBERS + SI]
    MOV MAX_NUM, AL

NOT_LARGER:
    LOOP FIND_MAX

    MOV AH, 02H
    MOV DL, MAX_NUM
    ADD DL, 30H
    INT 21H

    MOV AH, 4CH
    INT 21H

CODE_SEG ENDS
END START